### ISSUE TITLE
VMAPI not  pushes a changefeed event to CNS and the cmon proxy

### ISSUE THREAD

**Issue by tangfeng123** [joyent/sdc-vmapi#25] opened 2017-03-16 06:50 UTC
I have deploy the cmon and cmon-agent in my env. and use the command line curl could dsicover and get the instance's informaiton.
but Below steps is not work for me.
Container Creation
User creates a new container
VMAPI pushes a changefeed event to CNS and the proxy
CNS creates CNAME records of the form
When I create a new container finished, There is no CNAME record created.
So in my promethues system, all the instance show down like below.
Get https://500250f3-833b-470f-ad2d-10c6464a7e8f.cmon.bst-1.bstjpc.com:9163/metrics: dial tcp: lookup 500250f3-833b-470f-ad2d-10c6464a7e8f.cmon.bst-1.bstjpc.com on 203.241.132.34:53: no such host

is it cause by the vmapi version too low?
this is my vmapi version
release-20161027-20161027T010017Z-gaf77e72

any comment is appreciate.

**Comment by richardkiene** [comment] 2017-03-25 02:26
Hi @tangfeng123,

It looks like this is a duplicate of https://github.com/joyent/triton-cns/issues/5 and @arekinath is already working with you there. If it turns out that sdc-vmapi is the cause of this one of us can open a new issue here based on the findings from https://github.com/joyent/triton-cns/issues/5.

**Closed by richardkiene** 2017-03-25 02:26 UTC
